@echo off
setlocal

REM Always resolve plugins relative to this BAT file, not the current shell directory.
set "PLUGIN_DIR=%~dp0plugins"


REM Build the PC-side plugin bundle before starting Frida.
set "UNIVERSALIMGUI_PLUGIN_DIR=%PLUGIN_DIR%"
powershell -NoProfile -ExecutionPolicy Bypass -Command "$pluginDir=$env:UNIVERSALIMGUI_PLUGIN_DIR; $files=Get-ChildItem -LiteralPath $pluginDir -Filter '*.js' -File -ErrorAction SilentlyContinue; $out='// Generated by cmds.bat. Do not edit.\n'; $out+='(globalThis).__universalimguiPluginDir = '+($pluginDir|ConvertTo-Json -Compress)+';\n'; $out+='(globalThis).__universalimguiPluginFiles = {};\n'; foreach($f in $files){$name=$f.Name -replace '\\','\\\\' -replace '"','\"'; $code=[IO.File]::ReadAllText($f.FullName); $json=$code|ConvertTo-Json -Compress; $out+='(globalThis).__universalimguiPluginFiles["'+$name+'"] = '+$json+';\n'}; [IO.File]::WriteAllText('plugin_bundle.js',$out,(New-Object Text.UTF8Encoding($false)))"

frida -U -l frida-il2cpp-bridge.js -l plugin_bundle.js -l script.ts "Newton's Playground"

endlocal
