@echo off
setlocal

REM Always resolve plugins relative to this BAT file, not the current shell directory.
set "PLUGIN_DIR=C:\plugins"
set "BUNDLE_FILE=%~dp0plugin_bundle.js"
set "BRIDGE_FILE=%~dp0frida-il2cpp-bridge.js"
set "SCRIPT_FILE=%~dp0script.ts"

REM Build the PC-side plugin bundle before starting Frida.
set "UNIVERSALIMGUI_PLUGIN_DIR=%PLUGIN_DIR%"
set "UNIVERSALIMGUI_PLUGIN_BUNDLE=%BUNDLE_FILE%"
powershell -NoProfile -ExecutionPolicy Bypass -Command "$pluginDir=$env:UNIVERSALIMGUI_PLUGIN_DIR; $nl=[Environment]::NewLine; $files=Get-ChildItem -LiteralPath $pluginDir -Filter '*.js' -File -ErrorAction SilentlyContinue; $map=@{}; foreach($f in $files){$map[$f.Name]=[IO.File]::ReadAllText($f.FullName)}; $json=$map|ConvertTo-Json -Compress; $dir=$pluginDir|ConvertTo-Json -Compress; $out='// Generated by cmds.bat. Do not edit.'+$nl; $out+='(globalThis).__universalimguiPluginDir = '+$dir+';'+$nl; $out+='(globalThis).__universalimguiPluginFiles = '+$json+';'+$nl; [IO.File]::WriteAllText($env:UNIVERSALIMGUI_PLUGIN_BUNDLE,$out,(New-Object Text.UTF8Encoding($false)))"

frida -U -l "%BRIDGE_FILE%" -l "%BUNDLE_FILE%" -l "%SCRIPT_FILE%" "Newton's Playground"

endlocal
